export const education = [
    {
        logo: "https://i.imgur.com/NZSGKfu.png",
        name: "University of California, Irvine",
        shortName: "UC Irvine",
        time: "2012-2017",
        graduation: "2017",
        type: "Degree",
        degree: "Bachelor of Science",
        major: "Applied Mathematics",
        minor: "Environmental Science",
        coursework: [
            "Abstract Algebra",
            "Abstract/Discrete Mathematics",
            "Data Modeling", 
            "Differential Equations", 
            "Elementary Analysis", 
            "Group Theory", 
            "Linear Algebra", 
            "Multi-Variable Calculus", 
            "Numerical Analysis", 
            "Partial Differential Equations", 
            "Probability", 
            "Proofs and Theory"]
    }, 
    {
        logo: "https://i.imgur.com/J1kkzc0.png",
        name: "General Assembly",
        shortName: "GA",
        time: "2021",
        graduation: "2021",
        type: "Certification",
        degree: "",
        major: "Software Engineering",
        minor: "",
        coursework: [
            "Bootstrap", 
            "Django", 
            "Express", 
            "Git/Github",
            "HTML / CSS", 
            "JavaScript", 
            "jQuery", 
            "MongoDB", 
            "NodeJS", 
            "PostgreSQL",
            "Python", 
            "React", 
        ]
    },

    {
        logo: "https://i.imgur.com/ic6MzXS.png",
        name: "California State University, Fullerton",
        shortName: "Cal State Fullerton",
        time: "2022-2025",
        graduation: "2025",
        type: "Degree",
        degree: "Master of Science",
        major: "Computer Science",
        minor: "",
        coursework: [
            "Algorithm Engineering",
            "Assembly Language",
            "C++", 
            "Compilers",
            "Data Structures", 
            "Database Management", 
            "Operating Systems",
            "OOP", 
            "Python", 
            "Software Engineering",
        ]
    }
]